### ISSUE TITLE
Encrypt!!

### ISSUE THREAD

**Issue by ghost** [expIoiter/tantalus#1]
a good idea to make this for more practicial use would be encrypting your network traffic communication between the C2 and Infecfected using PyCrypto with AES Encryption

**Comment by codeuk** [comment]
you're right, that is a must for practical use. I'm currently in the process of developing a machine management system in GoLang which incorporates traffic encryption between the server and client(s). 👇

![image](https://user-images.githubusercontent.com/75194878/231194441-11249483-1eac-40e8-aedd-b9e9ae42eb55.png)

Let me know what else you think should be implemented, I value feedback :)

**Comment by ghost** [comment]
Some other things that would be cool include a payload builder i see you already have that but choosing the language of the payload would be great like being able to choose rust, C or Go ect. If you don't have it already maybe a crypter. Network Recon Tool and more features inside the C2. implementing a api key authentication system instead of just a basic login system that way you could even charge monthly fees for a professional version. Instead of flask for the webpage you could use Django as it has way more security, better performance, bigger community and support and imo better than flask for this use case.

**Comment by ghost** [comment]
Just some ideas to play around with yk, very cool & promising project btw
